wuvt/donate/models.py
import datetime
from wuvt import db


class Order(db.Model):
    __tablename__ = 'orders'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(255))
    email = db.Column(db.Unicode(255))
    phone = db.Column(db.Unicode(12))
    placed_date = db.Column(db.DateTime, default=datetime.datetime.utcnow)
    remote_addr = db.Column(db.Unicode(50))
    user_agent = db.Column(db.Unicode(255))
    dj = db.Column(db.UnicodeText)
    thank_on_air = db.Column(db.Boolean, default=False)
    first_time = db.Column(db.Boolean, default=True)
    donor_comment = db.Column(db.UnicodeText)

    premiums = db.Column(db.Unicode(255))               # mail, pickup, or none
    address1 = db.Column(db.Unicode(255))
    address2 = db.Column(db.Unicode(255))
    city = db.Column(db.Unicode(255))
    state = db.Column(db.Unicode(255))
    zipcode = db.Column(db.Integer)

    amount = db.Column(db.Integer)                      # amount charged (in US cents)
    recurring = db.Column(db.Boolean, unique=False, default=False)
    paid_date = db.Column(db.DateTime, default=None)
    shipped_date = db.Column(db.DateTime, default=None)

    tshirtsize = db.Column(db.Unicode(255))
    tshirtcolor = db.Column(db.Unicode(255))
    sweatshirtsize = db.Column(db.Unicode(255))

    method = db.Column(db.Unicode(255))
    custid = db.Column(db.Unicode(255))                 # used for Stripe recurrence
    comments = db.Column(db.UnicodeText)                # Internal use only. Staff can modify.

    def __init__(self, name, email, dj, thank_on_air, first_time, amount,
                 recurring):
        self.name = name
        self.email = email
        self.dj = dj
        self.thank_on_air = thank_on_air
        self.first_time = first_time
        self.amount = amount
        self.recurring = recurring

    def set_user_agent(self, user_agent):
        self.user_agent = str(user_agent)[:255]

    def set_premiums(self, premiums, tshirtsize, tshirtcolor, sweatshirtsize):
        self.premiums = premiums
        self.tshirtsize = tshirtsize
        self.tshirtcolor = tshirtcolor
        self.sweatshirtsize = sweatshirtsize

    def set_address(self, address1, address2, city, state, zipcode):
        self.address1 = address1
        self.address2 = address2
        self.city = city
        self.state = state
        self.zipcode = zipcode

    def set_paid(self, method, paid_date=None):
        self.method = method

        if paid_date is not None:
            self.paid_date = paid_date
        else:
            self.paid_date = datetime.datetime.utcnow()

    def set_shipped(self, shipped_date=None):
        if self.premiums is not None:
            # shipped & picked up are the same
            if shipped_date is not None:
                self.shipped_date = shipped_date
            else:
                self.shipped_date = datetime.datetime.utcnow()

wuvt/donate/__init__.py
import stripe
from flask import Blueprint
from wuvt import app

bp = Blueprint('donate', __name__)


def get_plan(id):
    stripe.api_key = app.config['STRIPE_SECRET_KEY']
    return stripe.Plan.retrieve(id)


def list_plans():
    stripe.api_key = app.config['STRIPE_SECRET_KEY']
    plans = stripe.Plan.all()['data']
    return sorted(plans, key=lambda x: x.amount)


def process_stripe_onetime(order, stripe_token, amount):
    stripe.api_key = app.config['STRIPE_SECRET_KEY']

    extra_data = {}
    if order.email is not None and len(order.email) > 0:
        extra_data['receipt_email'] = order.email

    try:
        # charge the customer using stripe_token
        stripe.Charge.create(
            amount=amount,
            currency="usd",
            source=stripe_token,
            metadata={'order_id': order.id},
            **extra_data)
    except stripe.CardError:
        return False

    return True


def process_stripe_recurring(order, stripe_token, plan, shipping_cost=0):
    stripe.api_key = app.config['STRIPE_SECRET_KEY']

    # create the customer using stripe_token
    try:
        customer = stripe.Customer.create(
            card=stripe_token,
            email=order.email
        )
    except stripe.CardError:
        return False

    order.custid = customer.id

    # bill for shipping, if applicable
    if shipping_cost > 0:
        stripe.InvoiceItem.create(
            customer=order.custid,
            amount=shipping_cost,
            currency="usd",
            description="One-time shipping fee")

    # create the subscription
    cust = stripe.Customer.retrieve(order.custid)
    cust.subscriptions.create(plan=plan)

    return True


from . import views

wuvt/donate/views.py
import datetime
from flask import flash, make_response, redirect, render_template, request, \
        url_for, Response
from wuvt import app
from wuvt import db
from wuvt import redis_conn
from wuvt.donate import bp
from wuvt.donate import get_plan, list_plans, mail, process_stripe_onetime, \
        process_stripe_recurring
from wuvt.donate.models import Order
from wuvt.donate.view_utils import load_premiums_config
from wuvt.view_utils import local_only


@bp.route('/onetime')
def donate_onetime():
    return render_template('donate/premium_form.html', active_flow='donate',
                           premiums_config=load_premiums_config())


@bp.route('/monthly')
def donate_recurring():
    return render_template('donate/recurring_form.html', plans=list_plans(),
                           active_flow='donate',
                           premiums_config=load_premiums_config())


def process_order(method):
    premiums_config = load_premiums_config()
    plan_id = request.form.get('plan', '')
    shipping_cost = 0

    if len(plan_id) > 0:
        recurring = True
        plan = get_plan(plan_id)

        if plan:
            amount = plan.amount
        else:
            return False, "Unknown plan ID"
    else:
        recurring = False
        amount_entry = request.form.get('amount', '').strip().lstrip('$')
        if len(amount_entry) <= 0:
            return False, "Please enter an amount to donate"

        amount = int(float(amount_entry) * 100)
        if amount <= 0:
            return False, "Amount must be greater than 0"

    order = Order(request.form.get('name', '').strip(),
                  request.form.get('email', '').strip(),
                  request.form.get('show', '').strip(),
                  request.form.get('onair', 'n') == 'y',
                  request.form.get('firsttime', 'n') == 'y',
                  amount, recurring)
    order.remote_addr = request.remote_addr
    order.set_user_agent(request.user_agent)

    if 'phone' in request.form:
        # Removes anything non-numeric from the phone string, so that we
        # no longer have exceptions when Mission Control users use something
        # like (540) 555-5555 instead of 540-555-5555 or 5405555555.
        order.phone = ''.join([char for char in request.form['phone'] if char
                               in "0123456789"])
        if len(order.phone) > 12:
            return False, "Phone number exceeded max length 12"

    if 'comment' in request.form:
        order.donor_comment = request.form['comment'].strip()

    if premiums_config['enabled'] and redis_conn.get('radiothon') == b"true":
        premiums = request.form.get('premiums', 'no')

        if premiums != "no":
            # TODO: check that these are valid
            order.set_premiums(premiums,
                               request.form.get('tshirtsize', None),
                               request.form.get('tshirtcolor', None),
                               request.form.get('sweatshirtsize', None))

        if premiums == "ship":
            # add shipping cost, if our order exceeds the minimum amount for
            # shipping cost (e.g., lowest tier has free shipping)
            if amount >= premiums_config['shipping_minimum']:
                shipping_cost = premiums_config['shipping_cost']

            order.set_address(request.form['address_1'],
                              request.form['address_2'],
                              request.form['city'],
                              request.form['state'],
                              request.form['zipcode'])

    db.session.add(order)
    try:
        db.session.commit()
    except:
        db.session.rollback()
        raise

    if method == 'stripe' or method == 'stripe_missioncontrol':
        token = request.form['stripe_token']
        if len(token) <= 0:
            return False, "stripe_token was empty"

        if recurring:
            if process_stripe_recurring(order, token, plan, shipping_cost):
                order.set_paid(method)
                mail.send_receipt(order)
            else:
                return False, "Your card was declined. Please try again with "\
                        "a different method of payment."
        else:
            if process_stripe_onetime(order, token, amount + shipping_cost):
                order.set_paid(method)
                mail.send_receipt(order)
            else:
                return False, "Your card was declined. Please try again with "\
                        "a different method of payment."
    else:
        if recurring:
            return False, "Only Stripe is supported for recurring payments."
        elif method != 'later':
            order.set_paid(method)

    try:
        db.session.commit()
    except:
        db.session.rollback()
        raise

    return True, "Thanks for your order!"


@bp.route('/process', methods=['POST'])
def process():
    errors = []
    premiums = request.form.get('premiums', 'no')
    if premiums != "no" and len(request.form['name']) <= 0:
        errors.append("Please enter your name")

    if premiums == "ship":
        # verify we included address information

        if len(request.form['address_1']) <= 0:
            errors.append("Please enter an address line 1")

        if len(request.form['city']) <= 0:
            errors.append("Please enter a city")

        if len(request.form['state']) <= 0:
            errors.append("Please enter a state")

        if len(request.form['zipcode']) <= 0:
            errors.append("Please enter a a ZIP code")

    if len(errors) > 0:
        return render_template('donate/error.html', messages=errors), 400

    success, msg = process_order('stripe')
    if success:
        return Response(msg)
    else:
        return render_template('donate/error.html', messages=[msg]), 400


@bp.route('/thanks')
def thanks():
    return render_template('donate/thanks.html')


@bp.route('/missioncontrol')
@local_only
def missioncontrol_index():
    cutoff = datetime.datetime.utcnow() - datetime.timedelta(hours=12)
    orders = Order.query.\
        filter(Order.placed_date > cutoff).\
        order_by(db.desc(Order.id)).limit(app.config['ARTISTS_PER_PAGE'])
    return render_template('donate/missioncontrol/index.html',
                           plans=list_plans(), orders=orders,
                           premiums_config=load_premiums_config())


@bp.route('/missioncontrol/process', methods=['POST'])
@local_only
def missioncontrol_process():
    success, msg = process_order(request.form['method'])
    if success:
        flash("The pledge was processed successfully.")
        return redirect(url_for('.missioncontrol_index'))
    else:
        return Response(msg), 400


@bp.route('/js/init.js')
def init_js():
    resp = make_response(render_template(
        'donate/init.js',
        premiums_config=load_premiums_config()))
    resp.headers['Content-Type'] = "application/javascript; charset=utf-8"
    return resp


@bp.route('/missioncontrol/js/donate_init.js')
@local_only
def missioncontrol_donate_js():
    resp = make_response(render_template(
        'donate/missioncontrol/donate.js',
        premiums_config=load_premiums_config()))
    resp.headers['Content-Type'] = "application/javascript; charset=utf-8"
    return resp

wuvt/templates/donate/error.html
{% extends "base.html" %}
{% block title %}Donation Error - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>Donation Error</h2>
    </header>

    <p>We're sorry, but there was a problem with your donation. The following
    error messages were returned:</p>

    <ul>
    {% for msg in messages -%}
        <li>{{ msg }}</li>
    {% endfor -%}
    </ul>

    <p>Please try to make your donation again. If you continue to get this
    error, please contact the station for assistance.</p>

    <footer>
    </footer>
</section>

{% endblock %}

wuvt/templates/donate/premium_form.html
{% extends "base.html" %}
{% block title %}Make a Donation - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>{% block donate_title %}Make a One-Time Donation{% endblock %}</h2>
    </header>

    <noscript><p>Sorry, but you'll need JavaScript enabled to donate. This
    allows us to process your donation without your credit card information
    ever touching our server.</p></noscript>

    <div id="donate_loading_message">
        <p>Please wait a few seconds for the donate form to load...</p>
    </div>

    <form action="{{ url_for('donate.process') }}" method="post"
            id="donate_form">
        <input type="hidden" name="_csrf_token" value="{{ csrf_token() }}" />
        <input type="hidden" name="stripe_token" id="id_stripe_token" value="" />

        <label>
            Your Name
            <input type="text" name="name" id="id_name" value="" />
        </label>

        {% block pledge_amount %}
        <label>
            Pledge Amount
            <input type="text" inputmode="numeric" name="amount"
                id="id_amount" pattern="\$?\d+(\.\d{2})?"
                placeholder="35.00" required="required" />
        </label>
        {% endblock %}

        <label>
            Email Address
            <input type="email" name="email" id="id_email" value=""
                placeholder="you@example.com" required="required" />
        </label>

        <label>
            Show to Credit
            <input type="text" name="show" id="id_show" value="" />
        </label>

        <label>
            Comment
            <input type="text" name="comment" id="id_comment" value="" />
        </label>

{% if premiums_config.enabled %}
        <label>
            Would you like any premiums?
        </label>

        <label>
            <input type="radio" name="premiums" id="id_premiums_no"
                value="no" checked="checked" />
            No, I'd like my entire donation to go towards WUVT
        </label>

        <label>
            <input type="radio" name="premiums" id="id_premiums_pickup"
                value="pickup" />
            Yes, I'll pick them up in 350 Squires Student Center
        </label>

        <label>
            <input type="radio" name="premiums" id="id_premiums_ship"
                value="ship" />
            Yes, ship them to me (+${{ premiums_config.shipping_cost // 100 }}, US only)
        </label>

        <div id="premium_fields">
        <p>
            <b>Note:</b> we are unable to guarantee premium availability if pledges
            are made outside of Radiothon week. If you make a recurring monthly
            donation, you will only be sent premiums for the first month.
        </p>

{% if premiums_config.premiums.tshirt %}
        <label>
            {{ premiums_config.premiums.tshirt.display }} Size
            <select id="id_tshirtsize" name="tshirtsize">
                {% for size in premiums_config.premiums.tshirt.sizes %}
                <option value="{{ size }}">{{ size }}</option>
                {% endfor %}
            </select>
        </label>

{% if premiums_config.premiums.tshirt.colors|length > 0 %}
        <label>
            {{ premiums_config.premiums.tshirt.display }} Color
            <select id="id_tshirtcolor" name="tshirtcolor">
                {% for color in premiums_config.premiums.tshirt.colors %}
                <option value="{{ color }}">{{ color }}</option>
                {%- endfor %}
            </select>
        </label>
{% endif %}
{% endif %}

{% if premiums_config.premiums.sweatshirt %}
        <label>
            {{ premiums_config.premiums.sweatshirt.display }} Size
            <select id="id_sweatshirtsize" name="sweatshirtsize">
                {% for size in premiums_config.premiums.sweatshirt.sizes %}
                <option value="{{ size }}">{{ size }}</option>
                {% endfor %}
            </select>
        </label>
{% endif %}
        </div>

        <div id="shipping_fields">
        <label>
            Address
            <input type="text" name="address_1" id="id_address_1" value="" />
        </label>

        <label>
            Address 2
            <input type="text" name="address_2" id="id_address_2" value="" />
        </label>

        <label>
            City
            <input type="text" name="city" id="id_city" value="" />
        </label>

        <label>
            State
            <input type="text" name="state" id="id_state" value="" />
        </label>

        <label>
            ZIP Code
            <input type="text" name="zipcode" id="id_zipcode" value="" />
        </label>
        </div>
{% endif %}

        <label>
            May we thank you publicly?
            <select name="onair" id="id_onair">
                <option value="y">Yes</option>
                <option value="n">No</option>
            </select>
        </label>

        <label>
            Is this your first time contributing?
            <select name="firsttime" id="id_firsttime">
                <option value="y">Yes</option>
                <option value="n" selected="selected">No</option>
            </select>
        </label>

        <button type="submit" class="btn-primary">Donate Now</button>
    </form>

    <footer></footer>
</section>
{% endblock %}
{% block js %}
{{ super() }}
<div id="extra_js">
<script src="{{ url_for('static', filename='js/donate.js') }}"></script>
<script src="https://checkout.stripe.com/checkout.js"></script>
<script src="{{ url_for('donate.init_js') }}"></script>
</div>
{% endblock %}

wuvt/templates/donate/recurring_form.html
{% extends "donate/premium_form.html" %}
{% block donate_title %}Make a Recurring Donation{% endblock %}
{% block pledge_amount %}
        <label>
            Monthly Pledge Amount
            <select name="plan" id="id_plan" required="required">
                <option value="" disabled="disabled">Select a plan</option>
                {% for plan in plans %}
                <option value="{{ plan.id }}" data-amount="{{ plan.amount }}">{{ plan.name }}</option>
                {% endfor %}
            </select>
        </label>
{% endblock %}

wuvt/templates/donate/thanks.html
{% extends "base.html" %}
{% block title %}Thank You - Donate Online - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>Thank You!</h2>
    </header>

    <p>Thank you for your donation! We have emailed you a receipt.</p>

    <footer>
    </footer>
</section>

{% endblock %}