wuvt/playlists/forms.py
from flask import current_app
from flask_wtf import FlaskForm
from wtforms import BooleanField, IntegerField, StringField, \
    ValidationError, validators
from .models import DJ


def strip_field(val):
    if isinstance(val, str):
        return val.strip()
    else:
        return val


def artist_validate(form, field):
    if field.data in current_app.config['TRACKMAN_ARTIST_PROHIBITED']:
        raise ValidationError("That artist may not be entered.")


def label_validate(form, field):
    if field.data in current_app.config['TRACKMAN_LABEL_PROHIBITED']:
        raise ValidationError("That label may not be entered.")


class DJRegisterForm(FlaskForm):
    airname = StringField('On-air Name', filters=[strip_field],
                          validators=[validators.Length(min=1, max=255),
                                      validators.DataRequired()])
    name = StringField('Real Name', filters=[strip_field],
                       validators=[validators.Length(min=1, max=255),
                                   validators.DataRequired()])
    email = StringField('Email Address', filters=[strip_field],
                        validators=[validators.Length(min=1, max=255),
                                    validators.Email(),
                                    validators.DataRequired()])
    phone = StringField('Phone Number', filters=[strip_field],
                        validators=[validators.Length(min=10, max=12),
                                    validators.DataRequired()])
    genres = StringField('Genres you can DJ', filters=[strip_field],
                         validators=[validators.Length(min=1, max=255),
                                     validators.DataRequired()])

    def validate_airname(self, field):
        matching = DJ.query.filter(DJ.airname == field.data).count()
        if matching > 0:
            raise ValidationError("Your on-air name must be unique.")


class DJReactivateForm(FlaskForm):
    email = StringField('Email Address', filters=[strip_field],
                        validators=[validators.Length(min=1, max=255),
                                    validators.Email(),
                                    validators.DataRequired()])
    phone = StringField('Phone Number', filters=[strip_field],
                        validators=[validators.Length(min=10, max=12),
                                    validators.DataRequired()])


class DJEditForm(FlaskForm):
    visible = BooleanField('Visible', validators=[validators.Optional()])
    email = StringField('Email Address', filters=[strip_field],
                        validators=[validators.Length(min=1, max=255),
                                    validators.Email(),
                                    validators.Optional()])
    phone = StringField('Phone Number', filters=[strip_field],
                        validators=[validators.Length(min=10, max=12),
                                    validators.Optional()])


class TrackAddForm(FlaskForm):
    title = StringField('Title', filters=[strip_field],
                        validators=[validators.DataRequired()])
    artist = StringField('Artist', filters=[strip_field],
                         validators=[artist_validate,
                                     validators.DataRequired()])
    album = StringField('Album', filters=[strip_field],
                        validators=[validators.DataRequired()])
    label = StringField('Label', filters=[strip_field],
                        validators=[label_validate,
                                    validators.DataRequired()])


class AutomationTrackLogForm(FlaskForm):
    password = StringField('Password')
    title = StringField('Title', filters=[strip_field])
    artist = StringField('Artist', filters=[strip_field])
    album = StringField('Album', filters=[strip_field])
    label = StringField('Label', filters=[strip_field])


class TrackLogEditForm(FlaskForm):
    title = StringField('Title', filters=[strip_field],
                        validators=[validators.DataRequired()])
    artist = StringField('Artist', filters=[strip_field],
                         validators=[artist_validate,
                                     validators.DataRequired()])
    album = StringField('Album', filters=[strip_field],
                        validators=[validators.DataRequired()])
    label = StringField('Label', filters=[strip_field],
                        validators=[label_validate,
                                    validators.DataRequired()])
    request = BooleanField('Request')
    vinyl = BooleanField('Vinyl')
    new = BooleanField('New')
    rotation = IntegerField('Rotation', default=1)
    played = StringField('Played')


class TrackLogForm(FlaskForm):
    track_id = IntegerField('Track ID')
    djset_id = IntegerField('DJSet ID')
    request = BooleanField('Request')
    vinyl = BooleanField('Vinyl')
    new = BooleanField('New')
    rotation = IntegerField('Rotation', default=1)
    played = StringField('Played')


class AirLogEditForm(FlaskForm):
    airtime = StringField('Air Time')
    logtype = IntegerField('Log Type', default=0)
    logid = IntegerField('Log ID', default=0)


class AirLogForm(FlaskForm):
    djset_id = IntegerField('DJSet ID')
    airtime = StringField('Air Time')
    logtype = IntegerField('Log Type', default=0)
    logid = IntegerField('Log ID', default=0)

wuvt/playlists/__init__.py
from flask import Blueprint

bp = Blueprint('playlists', __name__)

from . import views
from .views import trackinfo

wuvt/playlists/views.py
# NOTE: the .php filenames are kept so old URLs keep working

from flask import current_app, jsonify, make_response, render_template, \
        redirect, request, url_for, Response
import datetime
import dateutil.parser
import re
import requests
from feedwerk.atom import AtomFeed

from . import bp
from .view_utils import call_api, make_external, \
        tracklog_serialize, tracklog_full_serialize


def trackinfo():
    return call_api("/playlists/latest_track", 'GET')


#############################################################################
# Playlist Information
#############################################################################


@bp.route('/last15')
def last15():
    result = call_api("/playlists/last15", 'GET')

    if request.wants_json():
        return jsonify({
            'tracks': [tracklog_full_serialize(t) for t in result['tracks']],
        })

    return render_template('last15.html', tracklogs=result['tracks'],
                           feedlink=url_for('.last15_feed'))


@bp.route('/last15.atom')
def last15_feed():
    result = call_api("/playlists/last15", 'GET')
    tracks = result['tracks']
    feed = AtomFeed(
        "{0}: Last 15 Tracks".format(current_app.config['STATION_SHORT_NAME']),
        feed_url=request.url,
        url=make_external(url_for('.last15')))

    for tracklog in tracks:
        feed.add(
            "{artist}: '{title}'".format(
                artist=tracklog['track']['artist'],
                title=tracklog['track']['title']),
            "'{title}' by {artist} on {album} spun by {dj}".format(
                album=tracklog['track']['album'],
                artist=tracklog['track']['artist'],
                title=tracklog['track']['title'],
                dj=tracklog['dj']['airname']),
            url=make_external(url_for('.playlist',
                                      set_id=tracklog['djset_id'],
                                      _anchor="t{}".format(tracklog['id']))),
            author=tracklog['dj']['airname'],
            updated=dateutil.parser.parse(tracklog['played']),
            published=dateutil.parser.parse(tracklog['played']))

    return feed.get_response()


@bp.route('/playlists/latest_track')
@bp.route('/playlists/latest_track.php')
def latest_track():
    if request.wants_json():
        return jsonify(trackinfo())

    return Response("{artist} - {title}".format(**trackinfo()),
                    mimetype="text/plain")


@bp.route('/playlists/latest_track_clean')
@bp.route('/playlists/latest_track_clean.php')
def latest_track_clean():
    naughty_word_re = re.compile(
        r'shit|piss|fuck|cunt|cocksucker|tits|twat|asshole',
        re.IGNORECASE)

    track = trackinfo()
    for k, v in list(track.items()):
        if type(v) == str or type(v) == str:
            track[k] = naughty_word_re.sub('****', v)

    if request.wants_json():
        return jsonify(track)

    output = "{artist} - {title} [DJ: {dj}]".format(**track)
    return Response(output, mimetype="text/plain")


@bp.route('/playlists/latest_track_stream')
@bp.route('/playlists/latest_track_stream.php')
def latest_track_stream():
    return Response("""\
title={title}
artist={artist}
album={album}
description={description}
contact={contact}
""".format(**trackinfo()), mimetype="text/plain")


@bp.route('/playlists/live')
@bp.route('/live')
def live():
    url = "{0}/live".format(current_app.config['TRACKMAN_URL'])
    return redirect(url, 303)


# Playlist Archive (by date) {{{
@bp.route('/playlists/date')
def playlists_date():
    today = datetime.datetime.utcnow().replace(
        hour=0, minute=0, second=0, microsecond=0)
    return render_template('playlists_date_list.html', today=today)


@bp.route('/js/playlists_by_date_init.js')
def playlists_by_date_init_js():
    resp = make_response(render_template('playlists_by_date_init.js'))
    resp.headers['Content-Type'] = "application/javascript; charset=utf-8"
    return resp


@bp.route('/playlists/date/<int:year>/<int:month>/<int:day>')
def playlists_date_sets(year, month, day):
    r = requests.get('{0}/api/playlists/date/{1}/{2}/{3}'.format(
            current_app.config['TRACKMAN_URL'],
            year, month, day))
    status_code = r.status_code
    results = r.json()

    now = datetime.datetime.utcnow()
    start_date = dateutil.parser.parse(results['dtstart']).replace(tzinfo=None)
    next_date = start_date + datetime.timedelta(hours=24)
    next_url = url_for('.playlists_date_sets', year=next_date.year,
                       month=next_date.month, day=next_date.day)
    if next_date > now:
        next_url = None

    if start_date < now:
        prev_date = start_date - datetime.timedelta(hours=24)
        prev_url = url_for('.playlists_date_sets', year=prev_date.year,
                           month=prev_date.month, day=prev_date.day)
    else:
        prev_url = None

    results.update({
        'prev_url': prev_url,
        'next_url': next_url,
    })

    if request.wants_json():
        return jsonify(results), status_code

    return render_template(
        'playlists_date_sets.html',
        date=results['dtstart'],
        sets=results['sets'],
        prev_url=results['prev_url'],
        next_url=results['next_url']), status_code


@bp.route('/playlists/date/jump', methods=['POST'])
def playlists_date_jump():
    jumpdate = datetime.datetime.strptime(request.form['date'], "%Y-%m-%d")
    return redirect(url_for('.playlists_date_sets', year=jumpdate.year,
                            month=jumpdate.month, day=jumpdate.day))
# }}}


# Playlist Archive (by DJ) {{{
@bp.route('/playlists/dj')
def playlists_dj():
    results = call_api("/playlists/dj", 'GET')

    if request.wants_json():
        return jsonify(results)

    return render_template('playlists_dj_list.html', djs=results['djs'])


@bp.route('/playlists/dj/all')
def playlists_dj_all():
    results = call_api("/playlists/dj/all", 'GET')

    if request.wants_json():
        return jsonify(results)

    return render_template('playlists_dj_list_all.html', djs=results['djs'])


@bp.route('/playlists/dj/<int:dj_id>')
def playlists_dj_sets(dj_id):
    results = call_api("/playlists/dj/{0}", 'GET', dj_id)

    def cast_dates(t):
        if t['dtstart'] is not None:
            t['dtstart'] = dateutil.parser.parse(t['dtstart'])
        if t['dtend'] is not None:
            t['dtend'] = dateutil.parser.parse(t['dtend'])
        return t
    results['sets'] = [cast_dates(t) for t in results['sets']]

    if request.wants_json():
        return jsonify(results)

    return render_template('playlists_dj_sets.html',
                           dj=results['dj'], sets=results['sets'])
# }}}


# Charts {{{
@bp.route('/playlists/charts')
def charts_index():
    periodic_charts = [
        ('playlists.charts_albums', "Top albums"),
        ('playlists.charts_artists', "Top artists"),
        ('playlists.charts_tracks', "Top tracks"),
    ]
    return render_template('charts.html', periodic_charts=periodic_charts)


@bp.route('/playlists/charts/albums')
@bp.route('/playlists/charts/albums/<string:period>')
@bp.route('/playlists/charts/albums/<string:period>/<int:year>')
@bp.route('/playlists/charts/albums/<string:period>/<int:year>/<int:month>')
def charts_albums(period=None, year=None, month=None):
    if period == 'dj' and year is not None:
        return redirect(url_for('.charts_albums_dj', dj_id=year))

    if period is not None and year is not None and month is not None:
        results = call_api("/charts/albums/{0}/{1}/{2}", 'GET',
                           period, year, month)
    elif period is not None and year is not None:
        results = call_api("/charts/albums/{0}/{1}", 'GET',
                           period, year, month)
    elif period is not None:
        results = call_api("/charts/albums/{0}", 'GET',
                           period)
    else:
        results = call_api("/charts/albums", 'GET')

    if request.wants_json():
        return jsonify(results)

    return render_template('chart_albums.html',
                           start=results['start'],
                           end=results['end'],
                           results=results['results'])


@bp.route('/playlists/charts/dj/<int:dj_id>/albums')
def charts_albums_dj(dj_id):
    results = call_api("/charts/dj/{0}/albums", 'GET', dj_id)

    if request.wants_json():
        return jsonify(results)

    return render_template('chart_albums_dj.html',
                           dj=results['dj'],
                           results=results['results'])


@bp.route('/playlists/charts/artists')
@bp.route('/playlists/charts/artists/<string:period>')
@bp.route('/playlists/charts/artists/<string:period>/<int:year>')
@bp.route('/playlists/charts/artists/<string:period>/<int:year>/<int:month>')
def charts_artists(period=None, year=None, month=None):
    if period == 'dj' and year is not None:
        return redirect(url_for('.charts_artists_dj', dj_id=year))

    if period is not None and year is not None and month is not None:
        results = call_api("/charts/artists/{0}/{1}/{2}", 'GET',
                           period, year, month)
    elif period is not None and year is not None:
        results = call_api("/charts/artists/{0}/{1}", 'GET',
                           period, year, month)
    elif period is not None:
        results = call_api("/charts/artists/{0}", 'GET',
                           period)
    else:
        results = call_api("/charts/artists", 'GET')

    if request.wants_json():
        return jsonify(results)

    return render_template('chart_artists.html',
                           start=results['start'],
                           end=results['end'],
                           results=results['results'])


@bp.route('/playlists/charts/dj/<int:dj_id>/artists')
def charts_artists_dj(dj_id):
    results = call_api("/charts/dj/{0}/artists", 'GET', dj_id)

    if request.wants_json():
        return jsonify(results)

wuvt/templates/article.html
{% extends "base.html" %}
{% block title %}{{ article.title }} - {{ super() }}{% endblock %}
{% block content %}

<article class="article">
    <header>
        <h2>{{ article.title }}</h2>
        <h3>written by {{ article.author.name }} on <time datetime="{{ article.datetime|isodatetime }}" data-format="MMMM D, YYYY, HH:mm">{{ article.datetime|datetime("%B %d, %Y, %H:%M") }}</time></h3>
    </header>

{{ article.html_content|safe or article.html_summary|safe }}

    <footer>
        Filed under
        <a href="{{ url_for('blog.category', slug=article.category.slug) }}">{{ article.category.name }}</a>
    </footer>
</article>
{% endblock %}

wuvt/templates/chart_artists_dj.html
{% import "chart_macros.html" as macros %}
{% extends "base.html" %}
{% block title %}{{ dj.airname }} - Top Artists by DJ - Charts - {{ super() }}{% endblock %}
{% block content %}
<section>
<header>
    <h2>Charts: Top Artists by DJ</h2>
    <h3><a href="{{ url_for('playlists.playlists_dj_sets', dj_id=dj.id) }}">{{ dj.airname }}</a></h3>
</header>

{{ macros.render_chart_artists(results) }}
</section>
{% endblock %}

wuvt/templates/chart_dj_vinyl_spins.html
{% import "chart_macros.html" as macros %}
{% extends "base.html" %}
{% block title %}Top DJs by Vinyl Spins - Charts - {{ super() }}{% endblock %}
{% block content %}
<section>
<header>
    <h2>Charts: Top DJs by Vinyl Spins</h2>
</header>

{{ macros.render_chart_dj(results) }}
</section>
{% endblock %}

wuvt/templates/chart_macros.html
{% macro render_chart_albums(results) %}
<section class="tableSection">
<table class="tracklist tracklist-ranked chart">
    <thead>
        <th></th>
        <th>Artist</th>
        <th>Album</th>
        <th class="text-right">Spins</th>
    </thead>
    <tbody>
    {% for artist, album, spins, ranking in results %}
        <tr>
            <td>{{ ranking }}</td>
            <td>{{ artist }}</td>
            <td>{{ album }}</td>
            <td class="text-right">{{ spins }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endmacro %}

{% macro render_chart_artists(results) %}
<section class="tableSection">
<table class="tracklist tracklist-ranked chart">
    <thead>
        <th></th>
        <th>Artist</th>
        <th class="text-right">Spins</th>
    </thead>
    <tbody>
    {% for artist, spins, ranking in results %}
        <tr>
            <td>{{ ranking }}</td>
            <td>{{ artist }}</td>
            <td class="text-right">{{ spins }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endmacro %}

{% macro render_chart_tracks(results) %}
<section class="tableSection">
<table class="tracklist tracklist-ranked chart">
    <thead>
        <th></th>
        <th>Artist</th>
        <th>Track</th>
        <th>Album</th>
        <th class="text-right">Spins</th>
    </thead>
    <tbody>
    {% for track, spins, ranking in results %}
        <tr>
            <td>{{ ranking }}</td>
            <td>{{ track.artist }}</td>
            <td><a href="{{ url_for('playlists.playlists_track', track_id=track.id) }}">{{ track.title }}</a></td>
            <td>{{ track.album }}</td>
            <td class="text-right">{{ spins }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endmacro %}

{% macro render_chart_dj(results) %}
<section class="tableSection">
<table class="tracklist tracklist-ranked chart">
    <thead>
        <th></th>
        <th>DJ</th>
        <th class="text-right">Spins</th>
    </thead>
    <tbody>
    {% for dj, spins, ranking in results %}
        <tr>
            <td>{{ ranking }}</td>
            <td><a href="{{ url_for('playlists.playlists_dj_sets', dj_id=dj.id) }}">{{ dj.airname }}</a></td>
            <td class="text-right">{{ spins }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</section>
{% endmacro %}

wuvt/templates/chart_tracks.html
{% import "chart_macros.html" as macros %}
{% extends "base.html" %}
{% block title %}Top Tracks - Charts - {{ super() }}{% endblock %}
{% block content %}
<section>
<header>
    <h2>Charts: Top Tracks</h2>
    <h3>from <time datetime="{{ start|isodatetime }}" data-format="YYYY-MM-DD">{{ start|datetime("%Y-%m-%d") }}</time> to
        <time datetime="{{ end|isodatetime }}" data-format="YYYY-MM-DD">{{ end|datetime("%Y-%m-%d") }}</time></h3>
</header>

{{ macros.render_chart_tracks(results) }}
</section>
{% endblock %}

wuvt/templates/error400.html
{% extends "base.html" %}
{% block title %}Bad Request - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>Bad Request</h2>
    </header>

    <p>Sorry, but your browser sent a request that our server could not
    understand.</p>
</section>
{% endblock %}

wuvt/templates/error403.html
{% extends "base.html" %}
{% block title %}Forbidden - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>Forbidden</h2>
    </header>

    <p>Sorry, you don't have permission to access the requested resource. This
    attempt has been logged.</p>
</section>
{% endblock %}

wuvt/templates/error403_ipaccess.html
{% extends "base.html" %}
{% block title %}Forbidden - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>Forbidden</h2>
    </header>

    <p>Sorry, you don't have permission to access the requested resource
    because your IP address is not on the allowlist. If you're in the
    station, please disconnect from wifi and use the wired network.</p>

    <p>Your attempt to access this protected resource has been logged.</p>
</section>
{% endblock %}

wuvt/templates/error500.html
{% extends "base.html" %}
{% block title %}Internal Server Error - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>Internal Server Error</h2>
    </header>

    <p>We apologize for the inconvenience. Please try your request again
    later.</p>
</section>
{% endblock %}

wuvt/templates/page.html
{% set active_page = page.slug %}
{% extends "base.html" %}
{% block title %}{{ page.name }} - {{ super() }}{% endblock %}
{% block content %}

<section>
    <header>
        <h2>{{ page.name }}</h2>
    </header>

{{ page.html|safe }}

    <footer></footer>
</section>
{% endblock %}

wuvt/templates/playlists_date_list.html
{% set active_menu = "playlists_date" %}
{% extends "base.html" %}
{% block title %}Playlist Archive (by date) - {{ super() }}{% endblock %}

{% block content %}
<section>
    <header>
        <h2>Playlist Archive (by date)</h2>
    </header>

    <noscript>
        <p>Our default playlist history viewer requires JavaScript, but you can <a href="{{ url_for('.playlists_date_sets', year=today.year, month=today.month, day=today.day) }}">browse by day</a> instead.</p>
    </noscript>

    <div id="playlists_by_date">
    </div>

<section>
    <header>
        <h2>Jump to a Date</h2>
    </header>

    <form id="date_jump_form">
        <input type="date" name="date" id="date_entry" value="" placeholder="yyyy-mm-dd" />
        <button type="submit">Jump to Date</button>
    </form>
</section>
{% endblock %}

{% block js %}
{{ super() }}
<script src="{{ url_for('playlists.playlists_by_date_init_js') }}"></script>
{% endblock %}

wuvt/templates/playlists_dj_list_all.html
{% extends "base.html" %}
{% block title %}Playlist Archive (by DJ) - {{ super() }}{% endblock %}

{% block content %}
<section>
    <header>
        <h2>Playlist Archive (by DJ)</h2>
    </header>

    <ul>
        {% for dj in djs %}
        <li><a href="{{ url_for('playlists.playlists_dj_sets', dj_id=dj.id) }}">{{ dj.airname }}</a></li>
        {% endfor %}
    </ul>
</section>

<section class="pagination">
    <a href="{{ url_for('playlists.playlists_dj') }}">Show only current DJs</a>
</section>
{% endblock %}

wuvt/templates/playlists_dj_sets.html
{% extends "base.html" %}
{% block title %}{{ dj.airname }} - Playlist Archive (by DJ) - {{ super() }}{% endblock %}

{% block content %}
<section>
    <header>
        <h2>Playlist Archive (by DJ)</h2>
        <h3>{{ dj.airname }}</h3>
    </header>

{% for year, year_sets in sets|groupby('dtstart.year')|reverse %}
<details><summary id="year_{{ year }}">{{ year }}</summary>
    <ul id="year_{{ year }}_data">
        {%- for set in year_sets %}
        <li><a href="{{ url_for('playlists.playlist', set_id=set.id) }}"><time datetime="{{ set.dtstart|isodatetime }}" data-format="YYYY-MM-DD HH:mm">{{ set.dtstart|datetime("%Y-%m-%d %H:%M") }}</time>{% if set.dtend %}-<time datetime="{{ set.dtend|isodatetime }}" data-format="YYYY-MM-DD HH:mm">{{ set.dtend|datetime("%Y-%m-%d %H:%M") }}</time>{% endif %}</a></li>
        {%- endfor %}
    </ul></details>
{%- endfor %}
</section>

<section>
    <header>
        <h2>Charts</h2>
    </header>

    <ul>
        <li><a href="{{ url_for('playlists.charts_albums_dj', dj_id=dj.id) }}">Top albums for this DJ</a></li>
        <li><a href="{{ url_for('playlists.charts_artists_dj', dj_id=dj.id) }}">Top artists for this DJ</a></li>
        <li><a href="{{ url_for('playlists.charts_tracks_dj', dj_id=dj.id) }}">Top tracks for this DJ</a></li>
    </ul>
</section>
{% endblock %}

wuvt/templates/playlists_track.html
{% extends "base.html" %}
{% block title %}{{ track.title }} - {{ track.album }} - {{ track.artist }} - Playlist Archive - {{ super() }}{% endblock %}
{% block content %}
<section>
<header>
    <h2>{{ track.title }}</h2>
    <h3>On {{ track.album }} by {{ track.artist }}</h3>
</header>

<p>This track has been spun {{ tracklogs|length }} times.</p>

{% if track.recording_mbid %}
<p><a href="https://musicbrainz.org/recording/{{ track.recording_mbid }}" rel="external">See more information about this recording on MusicBrainz</a></p>
{% endif %}

<h2>Spins</h2>

{% for year, year_tracklogs in tracklogs|groupby('played.year') %}
<h4 id="year_{{ year }}">{{ year }}</h4>
<ul id="year_{{ year }}_data">
    {%- for tracklog in year_tracklogs %}
    {%- if tracklog.djset_id is not none and tracklog.djset_id > 0 %}
    <li><a href="{{ url_for('playlists.playlist', set_id=tracklog.djset_id) }}"><time datetime="{{ tracklog.played|isodatetime }}" data-format="YYYY-MM-DD HH:mm">{{ tracklog.played|datetime("%Y-%m-%d %H:%M") }}</time></a> by <a href="{{ url_for('playlists.playlists_dj_sets', dj_id=tracklog.dj.id) }}">{{ tracklog.dj.airname }}</a></li>
    {%- endif %}
    {%- endfor %}
</ul>
{% endfor %}
</section>
{% endblock %}